#!/usr/bin/env python3
"""Build the Redis API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Redis Platform',
        "color": '#DC382D',
        "closed": True,
        "stations": [
        ('Redis Core', (640, 260)),
        ('Cloud', (840, 460)),
        ('Enterprise', (640, 660)),
        ('Insight', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'Redis Core': 'https://apis.apis.io/apis/redis/redis-core/',
    'Cloud': 'https://apis.apis.io/apis/redis/redis-cloud-api/',
    'Enterprise': 'https://apis.apis.io/apis/redis/redis-enterprise-api/',
    'Insight': 'https://apis.apis.io/apis/redis/redis-insight/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Redis API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: redis/openapi · github.com/api-evangelist/redis',
        out_dir=Path(__file__).resolve().parent,
        out_basename='redis-subway-map',
        provider_id='redis',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
